stocks = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "AMZN": "Amazon.com, Inc.",
    "GOOGL": "Alphabet Inc.",
    "META": "Meta Platforms",
    "BRK-A": "Berkshire Hathaway Inc.",
    "V": "Visa Inc.",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart Inc.",
    "JPM": "JPMorgan Chase & Co.",
    "MA": "Mastercard Incorporated",
    "PG": "The Procter & Gamble Company",
    "UNH": "UnitedHealth Group Incorporated",
    "DIS": "The Walt Disney Company",
    "HD": "The Home Depot, Inc.",
    "BAC": "Bank of America Corporation",
    "NVDA": "NVIDIA Corporation",
    "PYPL": "PayPal Holdings, Inc.",
    "CMCSA": "Comcast Corporation",
    "NFLX": "Netflix, Inc.",
    "ADBE": "Adobe Inc.",
    "KO": "The Coca-Cola Company",
    "NKE": "NIKE, Inc.",
    "MRK": "Merck & Co., Inc.",
    "PEP": "PepsiCo, Inc.",
    "T": "AT&T Inc.",
    "PFE": "Pfizer Inc.",
    "INTC": "Intel Corporation",
    "CSCO": "Cisco Systems, Inc.",
    "CRM": "salesforce.com, inc.",
    "XOM": "Exxon Mobil Corporation",
}
