name: Check Files

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/check-files.yml"
      - "**.py"

jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Check files
        shell: bash
        run: .github/scripts/check-files.sh
